import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Button from 'react-bootstrap/Button';
import { useSession, signIn, signOut  ,getSession} from "next-auth/react"
import LoginPage from '@/Components/LoginPage';

import useSWR from 'swr'
const fetcher = (...args) => fetch(...args).then(res => res.json())
export default function Home() {

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='d-flex justify-content-center align-items-center rounded overflow-hidden' style={{backgroundColor : "#D3D4D5" , height : "100dvh"}}>
          <LoginPage />
      </main>
    </>
  )
}

Home.layout = "L1"

export async function getServerSideProps (context) {
  const session = await getSession({req : context.req})
  if(session) {
    return {
      redirect : {
        destination : "/AdminDashboard"
      }
    }
  }
  return { props : {session}}
}