import Head from 'next/head'
import { getSession} from "next-auth/react"
import LoginPage from '@/Components/LoginPage';


const Home = () => {
  
  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='d-flex justify-content-center align-items-center rounded overflow-hidden' style={{backgroundColor : "#D3D4D5" , height : "100dvh"}}>
          <LoginPage />
      </main>
    </>
  )
}

Home.layout = "L1"



export async function getServerSideProps(context) {
  try {
    const session = await getSession({ req: context.req });

    if (session) {
      return {
        redirect: {
          destination: "/AdminDashboard",
          permanent: false, // Set to false to allow redirects to work on subsequent visits
        },
      };
    }

    return { props: { session } };
  } catch (error) {
    console.error("Error in getServerSideProps:", error);

    return {
      redirect: {
        destination: "/500", // Redirect to a generic error page
        permanent: false,
      },
    };
  }
}